- name: http test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: set flag
      set_fact:
        portFlag: 0

    - name: Get available port
      include_tasks: registerPort.yml
      loop: "{{ range(8080, 8090) | list }}"
      loop_control:
        loop_var: iPort
      no_log: true

    - name: test app
      block:
        - name: start app
          shell: "java -jar {{ item }} --server.port={{ freePort }} >/dev/null 2>&1 &"
          async: 3600
          poll: 0
          with_fileglob: "{{ inventory_dir }}/*.jar"
        - name: Wait for port
          wait_for:
            port: "{{ freePort }}"
            delay: 5
            timeout: 120
        - name: http request
          uri:
            url: "http://localhost:{{ freePort }}/hello"
        - name: stop app
          shell: "kill -s TERM $(lsof -t -i TCP:{{ freePort }})"
      when: freePort is defined