- name: http test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: set flag
      set_fact:
        portFlag: 0

    - name: get available port
      include_tasks: registerPort.yml
      loop: "{{ range(8080, 8090) | list }}"
      loop_control:
        loop_var: iPort
      no_log: false

    - name: print app port
      debug:
        msg: "{{ freePort }}"

    - name: test app
      block:
        - name: start app
          shell: export JENKINS_NODE_COOKIE=dontKillMe && nohup java -jar {{ item }} --server.port={{ freePort }} </dev/null >/dev/null 2>&1 &
          with_fileglob: "{{ inventory_dir }}/*.jar"
        - name: wait for port
          wait_for:
            port: "{{ freePort }}"
            delay: 5
            timeout: 120
        - name: http request
          uri:
            url: "http://localhost:{{ freePort }}/hello"
            return_content: yes
          register: app_response
        - name: print response
          debug:
            msg: "{{ app_response }}"
        - name: stop app
          shell: "kill -s TERM $(lsof -t -i TCP:{{ freePort }})"
      when: freePort is defined