apiVersion: v1
kind: Service
metadata:
  name: {{ include "HiApp.fullname" . }}
  labels:
    {{- include "HiApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "HiApp.selectorLabels" . | nindent 4 }}
